import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function fetchOgImage(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml",
      },
      signal: AbortSignal.timeout(7000),
    })
    if (!res.ok) return null
    const html = await res.text()
    const match =
      html.match(/<meta[^>]*property=["']og:image["'][^>]*content=["']([^"']+)["']/i) ||
      html.match(/<meta[^>]*content=["']([^"']+)["'][^>]*property=["']og:image["']/i)
    return match?.[1] ?? null
  } catch {
    return null
  }
}

function avatarFallback(name: string): string {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=1A0A2E&color=F5E642&size=400`
}

async function resolveImage(profileUrl: string, name: string): Promise<string> {
  console.log(`  → fetching image from ${profileUrl}`)
  const img = await fetchOgImage(profileUrl)
  if (img) {
    console.log(`  ✓ got real image`)
    return img
  }
  console.log(`  ✗ fallback to avatar`)
  return avatarFallback(name)
}

async function main() {
  await prisma.campaignCreator.deleteMany()
  await prisma.creatorResearch.deleteMany()
  await prisma.proposal.deleteMany()
  await prisma.campaign.deleteMany()
  await prisma.creator.deleteMany()
  await prisma.agencySettings.deleteMany()

  await prisma.agencySettings.create({
    data: {
      agencyName: "Lumos",
      primaryColor: "#C8102E",
      secondaryColor: "#1A1A2E",
      accentColor: "#F5A623",
      tagline: "MENA's Premier Influencer Marketing Agency",
      contactEmail: "hello@lumos.agency",
      website: "https://lumos.agency",
      serviceMarkup: 0.12,
      agencyCommission: 0.20,
      defaultCurrency: "USD",
    },
  })

  const creatorsRaw = [
    {
      name: "ABSI",
      nameAr: "عبسي",
      bio: "Jordanian Kick gaming streamer and one of the biggest Arabic live-streaming personalities. Known for FPS gameplay, high-energy streams, and a massive loyal Arabic-speaking community across the GCC.",
      profileUrl: "https://kick.com/absi",
      country: "Jordan",
      city: "Amman",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Gaming & Esports"]),
      platforms: JSON.stringify(["Kick", "YouTube"]),
      kickHandle: "absi",
      kickFollowers: 1800000,
      kickAvgCCV: 28000,
      youtubeHandle: "ABSI",
      youtubeSubscribers: 980000,
      youtubeAvgViews: 350000,
      audienceGenderSplit: JSON.stringify({ male: 88, female: 12 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 30, "18-24": 48, "25-34": 18, "35-44": 3, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Jordan", percentage: 28 },
        { country: "Saudi Arabia", percentage: 30 },
        { country: "Egypt", percentage: 18 },
        { country: "UAE", percentage: 12 },
        { country: "Kuwait", percentage: 12 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "Esports", "Streaming", "FPS"]),
      rateKickStream: 8000,
      rateYouTubeIntegration: 12000,
      rateYouTubeDedicated: 28000,
      rateLiveEventAppearance: 20000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["GFuel", "HyperX", "Kick.com"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "kick", "jordan", "arabic", "mega"]),
      isActive: true,
    },
    {
      name: "Ashraf Mido",
      nameAr: "أشرف ميدو",
      bio: "Egyptian gaming YouTuber with one of the biggest gaming channels in the Arab world. Creates FIFA, action, and lifestyle content. Known for high production quality and consistent uploads.",
      profileUrl: "https://www.youtube.com/@AshrafMido",
      country: "Egypt",
      city: "Cairo",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Gaming & Esports", "Comedy & Entertainment"]),
      platforms: JSON.stringify(["YouTube", "TikTok", "Instagram"]),
      youtubeHandle: "AshrafMido",
      youtubeSubscribers: 8200000,
      youtubeAvgViews: 1500000,
      tiktokHandle: "ashrafmido",
      tiktokFollowers: 2100000,
      tiktokAvgViews: 800000,
      instagramHandle: "ashrafmido",
      instagramFollowers: 1400000,
      instagramAvgLikes: 45000,
      audienceGenderSplit: JSON.stringify({ male: 82, female: 18 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 32, "18-24": 46, "25-34": 18, "35-44": 3, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Egypt", percentage: 48 },
        { country: "Saudi Arabia", percentage: 22 },
        { country: "UAE", percentage: 12 },
        { country: "Kuwait", percentage: 8 },
        { country: "Jordan", percentage: 10 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "FIFA", "YouTube", "Entertainment"]),
      rateYouTubeIntegration: 35000,
      rateYouTubeDedicated: 75000,
      rateTikTokVideo: 18000,
      rateInstagramPost: 15000,
      rateInstagramReel: 22000,
      rateLiveEventAppearance: 50000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["EA Sports", "PUBG Mobile", "Pepsi Egypt", "Vodafone Egypt"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "youtube", "egypt", "mega", "arabic"]),
      isActive: true,
    },
    {
      name: "Faris Al-Sultan",
      nameAr: "فارس السلطان",
      bio: "Kuwaiti entertainment creator blending comedy, lifestyle, and pop culture commentary. One of Kuwait's most recognized digital personalities with a pan-GCC audience.",
      profileUrl: "https://www.youtube.com/@FarisAlSultan",
      country: "Kuwait",
      city: "Kuwait City",
      language: JSON.stringify(["Arabic"]),
      tier: "MACRO",
      niches: JSON.stringify(["Comedy & Entertainment", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["YouTube", "Instagram", "Snapchat"]),
      youtubeHandle: "FarisAlSultan",
      youtubeSubscribers: 2400000,
      youtubeAvgViews: 420000,
      instagramHandle: "faris.alsultan",
      instagramFollowers: 1100000,
      instagramAvgLikes: 38000,
      snapchatHandle: "farisalsultan",
      snapchatFollowers: 650000,
      audienceGenderSplit: JSON.stringify({ male: 55, female: 45 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 22, "18-24": 44, "25-34": 26, "35-44": 7, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Kuwait", percentage: 35 },
        { country: "Saudi Arabia", percentage: 30 },
        { country: "UAE", percentage: 15 },
        { country: "Bahrain", percentage: 10 },
        { country: "Qatar", percentage: 10 },
      ]),
      audienceInterests: JSON.stringify(["Comedy", "Lifestyle", "GCC Culture", "Entertainment"]),
      rateYouTubeIntegration: 18000,
      rateYouTubeDedicated: 40000,
      rateInstagramPost: 10000,
      rateInstagramReel: 15000,
      rateSnapchatStory: 8000,
      rateLiveEventAppearance: 30000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Zain Kuwait", "Alshaya Group", "McDonald's Kuwait", "Samsung KW"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["comedy", "kuwait", "arabic", "macro", "gcc"]),
      isActive: true,
    },
    {
      name: "Mas3od",
      nameAr: "معسود",
      bio: "Saudi gaming and entertainment creator known for FIFA content, vlogs, and reaction videos. Hugely popular with Saudi and GCC youth, combining humor with gaming culture.",
      profileUrl: "https://www.youtube.com/@mas3od",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Gaming & Esports", "Comedy & Entertainment"]),
      platforms: JSON.stringify(["YouTube", "TikTok", "Instagram"]),
      youtubeHandle: "mas3od",
      youtubeSubscribers: 5800000,
      youtubeAvgViews: 1100000,
      tiktokHandle: "mas3od",
      tiktokFollowers: 3200000,
      tiktokAvgViews: 1400000,
      instagramHandle: "mas3od",
      instagramFollowers: 1800000,
      instagramAvgLikes: 62000,
      audienceGenderSplit: JSON.stringify({ male: 80, female: 20 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 35, "18-24": 46, "25-34": 15, "35-44": 3, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 62 },
        { country: "UAE", percentage: 12 },
        { country: "Kuwait", percentage: 10 },
        { country: "Egypt", percentage: 8 },
        { country: "Bahrain", percentage: 8 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "FIFA", "Saudi Culture", "Comedy"]),
      rateYouTubeIntegration: 40000,
      rateYouTubeDedicated: 85000,
      rateTikTokVideo: 30000,
      rateInstagramPost: 20000,
      rateInstagramReel: 32000,
      rateLiveEventAppearance: 65000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["STC", "stc play", "Pepsi KSA", "EA Sports FIFA", "Noon"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "saudi", "mega", "arabic", "tiktok"]),
      isActive: true,
    },
    {
      name: "Bader Al-Shu'aibi",
      nameAr: "بدر الشعيبي",
      bio: "Kuwaiti comedian, actor, and content creator famous for his sketch comedy and satirical takes on Gulf society. One of the most beloved comedians in the Arab world with a massive pan-Arab following.",
      profileUrl: "https://www.youtube.com/@baderalshuaibi",
      country: "Kuwait",
      city: "Kuwait City",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Comedy & Entertainment"]),
      platforms: JSON.stringify(["YouTube", "Instagram", "TikTok", "Snapchat"]),
      youtubeHandle: "baderalshuaibi",
      youtubeSubscribers: 7200000,
      youtubeAvgViews: 1800000,
      instagramHandle: "baderalshuaibi",
      instagramFollowers: 4500000,
      instagramAvgLikes: 180000,
      tiktokHandle: "baderalshuaibi",
      tiktokFollowers: 2800000,
      tiktokAvgViews: 1200000,
      snapchatHandle: "baderalshuaibi",
      snapchatFollowers: 2200000,
      audienceGenderSplit: JSON.stringify({ male: 58, female: 42 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 28, "18-24": 44, "25-34": 22, "35-44": 5, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Kuwait", percentage: 28 },
        { country: "Saudi Arabia", percentage: 35 },
        { country: "UAE", percentage: 15 },
        { country: "Egypt", percentage: 10 },
        { country: "Bahrain", percentage: 12 },
      ]),
      audienceInterests: JSON.stringify(["Comedy", "Satire", "Gulf Culture", "Entertainment"]),
      rateYouTubeIntegration: 60000,
      rateYouTubeDedicated: 130000,
      rateInstagramPost: 45000,
      rateInstagramReel: 70000,
      rateTikTokVideo: 50000,
      rateSnapchatStory: 35000,
      rateLiveEventAppearance: 120000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Zain Kuwait", "Pepsi", "KFC", "Samsung", "Alshaya"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["comedy", "kuwait", "mega", "arabic", "actor"]),
      isActive: true,
    },
    {
      name: "Mohammed Alshaikh",
      nameAr: "محمد الشيخ",
      bio: "Saudi tech YouTuber delivering in-depth smartphone and gadget reviews in Arabic. Trusted voice in the Arabic tech community with a reputation for honest, detailed analysis.",
      profileUrl: "https://www.youtube.com/@MohammedAlshaikh",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic"]),
      tier: "MID",
      niches: JSON.stringify(["Tech & Gadgets"]),
      platforms: JSON.stringify(["YouTube", "Twitter/X", "Instagram"]),
      youtubeHandle: "MohammedAlshaikh",
      youtubeSubscribers: 980000,
      youtubeAvgViews: 210000,
      twitterHandle: "mohammedalshaikh",
      twitterFollowers: 320000,
      instagramHandle: "mohammedalshaikh",
      instagramFollowers: 280000,
      instagramAvgLikes: 8500,
      audienceGenderSplit: JSON.stringify({ male: 86, female: 14 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 12, "18-24": 38, "25-34": 36, "35-44": 11, "45+": 3 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 55 },
        { country: "UAE", percentage: 16 },
        { country: "Kuwait", percentage: 10 },
        { country: "Egypt", percentage: 10 },
        { country: "Jordan", percentage: 9 },
      ]),
      audienceInterests: JSON.stringify(["Tech", "Smartphones", "Gadgets", "Reviews"]),
      rateYouTubeIntegration: 12000,
      rateYouTubeDedicated: 26000,
      rateYouTubeShort: 4000,
      rateInstagramPost: 5000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Samsung KSA", "Huawei", "Xiaomi MENA", "Honor", "Anker"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["tech", "saudi", "arabic", "mid", "youtube"]),
      isActive: true,
    },
    {
      name: "Anas Marwah",
      nameAr: "أنس مروة",
      bio: "Syrian lifestyle vlogger based in Saudi Arabia. Documents daily life, travel, family, and food with an authentic style that resonates across the Arab world. One of YouTube's top Arabic lifestyle creators.",
      profileUrl: "https://www.youtube.com/@AnasMarwah",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Lifestyle & Fashion", "Travel", "Food & Restaurants"]),
      platforms: JSON.stringify(["YouTube", "Instagram", "TikTok"]),
      youtubeHandle: "AnasMarwah",
      youtubeSubscribers: 6100000,
      youtubeAvgViews: 1200000,
      instagramHandle: "anasmarwah",
      instagramFollowers: 3200000,
      instagramAvgLikes: 95000,
      tiktokHandle: "anasmarwah",
      tiktokFollowers: 2400000,
      tiktokAvgViews: 900000,
      audienceGenderSplit: JSON.stringify({ male: 50, female: 50 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 20, "18-24": 42, "25-34": 28, "35-44": 8, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 42 },
        { country: "Syria", percentage: 15 },
        { country: "UAE", percentage: 15 },
        { country: "Egypt", percentage: 15 },
        { country: "Jordan", percentage: 13 },
      ]),
      audienceInterests: JSON.stringify(["Lifestyle", "Family", "Food", "Travel", "Vlogging"]),
      rateYouTubeIntegration: 42000,
      rateYouTubeDedicated: 90000,
      rateInstagramPost: 30000,
      rateInstagramReel: 48000,
      rateTikTokVideo: 28000,
      rateLiveEventAppearance: 60000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Noon", "Jarir", "stc", "Almarai", "Nescafé Arabia"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["lifestyle", "vlog", "arabic", "mega", "family"]),
      isActive: true,
    },
    {
      name: "Bassem Youssef",
      nameAr: "باسم يوسف",
      bio: "Egyptian satirist, comedian, and media personality. Creator of Al-Bernameg — the Arab world's most-watched political satire show. Now active globally on digital platforms with commentary on politics and culture.",
      profileUrl: "https://www.youtube.com/@bassemyoussef",
      country: "Egypt",
      city: "Cairo",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MEGA",
      niches: JSON.stringify(["Comedy & Entertainment", "Education"]),
      platforms: JSON.stringify(["YouTube", "Instagram", "Twitter/X"]),
      youtubeHandle: "bassemyoussef",
      youtubeSubscribers: 5400000,
      youtubeAvgViews: 900000,
      instagramHandle: "bassemyoussef",
      instagramFollowers: 6200000,
      instagramAvgLikes: 210000,
      twitterHandle: "bassemyoussef",
      twitterFollowers: 8100000,
      audienceGenderSplit: JSON.stringify({ male: 55, female: 45 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 8, "18-24": 32, "25-34": 38, "35-44": 16, "45+": 6 }),
      audienceTopCountries: JSON.stringify([
        { country: "Egypt", percentage: 35 },
        { country: "Saudi Arabia", percentage: 20 },
        { country: "UAE", percentage: 15 },
        { country: "United States", percentage: 15 },
        { country: "United Kingdom", percentage: 15 },
      ]),
      audienceInterests: JSON.stringify(["Satire", "Politics", "Comedy", "Media", "Culture"]),
      rateYouTubeIntegration: 80000,
      rateYouTubeDedicated: 180000,
      rateInstagramPost: 65000,
      rateLiveEventAppearance: 200000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["MBC", "Netflix MENA", "Cairo International Film Festival"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["comedy", "satire", "egypt", "mega", "global", "bilingual"]),
      isActive: true,
    },
    {
      name: "Nas Daily",
      nameAr: null,
      bio: "Palestinian creator Nuseir Yassin — one of the world's most viral content creators. Famous for one-minute daily videos celebrating people and places globally. Hugely followed across TikTok, Instagram, and Facebook.",
      profileUrl: "https://www.tiktok.com/@nasdaily",
      country: "Palestinian Territories",
      city: "Tel Aviv",
      language: JSON.stringify(["English", "Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Travel", "Education", "Comedy & Entertainment"]),
      platforms: JSON.stringify(["TikTok", "Instagram", "YouTube"]),
      tiktokHandle: "nasdaily",
      tiktokFollowers: 22000000,
      tiktokAvgViews: 8000000,
      instagramHandle: "nasdaily",
      instagramFollowers: 10500000,
      instagramAvgLikes: 280000,
      youtubeHandle: "NasDaily",
      youtubeSubscribers: 3800000,
      youtubeAvgViews: 1200000,
      audienceGenderSplit: JSON.stringify({ male: 48, female: 52 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 18, "18-24": 40, "25-34": 30, "35-44": 9, "45+": 3 }),
      audienceTopCountries: JSON.stringify([
        { country: "United States", percentage: 22 },
        { country: "India", percentage: 15 },
        { country: "Philippines", percentage: 10 },
        { country: "Saudi Arabia", percentage: 12 },
        { country: "Egypt", percentage: 11 },
      ]),
      audienceInterests: JSON.stringify(["Travel", "People", "World Culture", "Positivity", "Education"]),
      rateTikTokVideo: 120000,
      rateInstagramPost: 90000,
      rateInstagramReel: 140000,
      rateYouTubeIntegration: 100000,
      rateLiveEventAppearance: 250000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Airbnb", "Google", "PayPal", "Mastercard", "Booking.com"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["global", "travel", "viral", "mega", "english", "nasdaily"]),
      isActive: true,
    },
    {
      name: "Salma Rachid",
      nameAr: "سلمى رشيد",
      bio: "Moroccan pop star and digital creator with a massive following across North Africa and the Arab world. Creates music, lifestyle content, and beauty collaborations in Arabic and French.",
      profileUrl: "https://www.youtube.com/@SalmaRachid",
      country: "Morocco",
      city: "Casablanca",
      language: JSON.stringify(["Arabic", "French"]),
      tier: "MACRO",
      niches: JSON.stringify(["Music & Entertainment", "Lifestyle & Fashion", "Beauty & Skincare"]),
      platforms: JSON.stringify(["Instagram", "YouTube", "TikTok"]),
      instagramHandle: "salmarachid",
      instagramFollowers: 2800000,
      instagramAvgLikes: 85000,
      youtubeHandle: "SalmaRachid",
      youtubeSubscribers: 1100000,
      youtubeAvgViews: 4500000,
      tiktokHandle: "salmarachid",
      tiktokFollowers: 1400000,
      tiktokAvgViews: 600000,
      audienceGenderSplit: JSON.stringify({ male: 38, female: 62 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 25, "18-24": 45, "25-34": 22, "35-44": 6, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Morocco", percentage: 38 },
        { country: "Algeria", percentage: 18 },
        { country: "Tunisia", percentage: 12 },
        { country: "France", percentage: 15 },
        { country: "UAE", percentage: 17 },
      ]),
      audienceInterests: JSON.stringify(["Music", "Pop", "Lifestyle", "Beauty", "Fashion", "North Africa"]),
      rateInstagramPost: 22000,
      rateInstagramReel: 35000,
      rateInstagramStory: 8000,
      rateYouTubeIntegration: 30000,
      rateTikTokVideo: 20000,
      rateLiveEventAppearance: 80000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["L'Oreal Paris", "Garnier", "Rotana Music", "Royal Air Maroc", "Infinix"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["music", "morocco", "arabic", "macro", "french", "pop"]),
      isActive: true,
    },
  ]

  console.log("\n🔍 Fetching real profile images...\n")

  for (const raw of creatorsRaw) {
    const { profileUrl, ...rest } = raw
    console.log(`[${rest.name}]`)
    const profileImageUrl = await resolveImage(profileUrl, rest.name)

    await prisma.creator.create({
      data: { ...rest, profileImageUrl } as any,
    })
    console.log(`  ✅ saved\n`)
  }

  console.log(`✅ Seeded ${creatorsRaw.length} real MENA creators`)
  console.log("✅ Agency settings created")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
