import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  // Clear existing data
  await prisma.campaignCreator.deleteMany()
  await prisma.creatorResearch.deleteMany()
  await prisma.proposal.deleteMany()
  await prisma.campaign.deleteMany()
  await prisma.creator.deleteMany()
  await prisma.agencySettings.deleteMany()

  // Create agency settings
  await prisma.agencySettings.create({
    data: {
      agencyName: "Flamenzi",
      primaryColor: "#C8102E",
      secondaryColor: "#1A1A2E",
      accentColor: "#F5A623",
      tagline: "MENA's Premier Influencer Marketing Agency",
      contactEmail: "hello@flamenzi.com",
      website: "https://flamenzi.com",
      serviceMarkup: 0.12,
      agencyCommission: 0.20,
      defaultCurrency: "USD",
    },
  })

  // 20 creators
  const creators = [
    // 1. Saudi gaming streamer
    {
      name: "Abdullah Al-Rashidi",
      nameAr: "عبدالله الراشدي",
      bio: "Saudi gaming streamer and content creator specializing in FPS and Battle Royale games. Known for high-energy streams and community engagement. Based in Riyadh with a loyal Arabic-speaking audience across the GCC.",
      profileImageUrl: "https://i.pravatar.cc/400?img=1",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MACRO",
      niches: JSON.stringify(["Gaming & Esports"]),
      platforms: JSON.stringify(["Twitch", "YouTube"]),
      twitchHandle: "AbdullahPlays",
      twitchFollowers: 890000,
      twitchAvgCCV: 12000,
      youtubeHandle: "AbdullahPlaysYT",
      youtubeSubscribers: 1200000,
      youtubeAvgViews: 280000,
      audienceGenderSplit: JSON.stringify({ male: 82, female: 18 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 22, "18-24": 45, "25-34": 25, "35-44": 6, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 55 },
        { country: "UAE", percentage: 18 },
        { country: "Kuwait", percentage: 10 },
        { country: "Egypt", percentage: 8 },
        { country: "Jordan", percentage: 9 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "Esports", "Tech", "Streaming"]),
      rateTwitchStream: 4500,
      rateYouTubeIntegration: 8000,
      rateYouTubeDedicated: 18000,
      rateYouTubeShort: 2500,
      rateLiveEventAppearance: 12000,
      exclusivityStatus: "SOFT",
      managedByFlamenzi: true,
      pastBrandCollabs: JSON.stringify(["STC", "Extra Stores", "Razer", "Alienware", "Mountain Dew"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "twitch", "arabic", "top-creator"]),
      isActive: true,
    },
    // 2. UAE lifestyle influencer
    {
      name: "Layla Al-Mansoori",
      nameAr: "ليلى المنصوري",
      bio: "Dubai-based lifestyle and fashion influencer documenting the glamorous side of UAE living. Bilingual content in Arabic and English. Known for aspirational yet authentic content about fashion, dining, and travel.",
      profileImageUrl: "https://i.pravatar.cc/400?img=5",
      country: "UAE",
      city: "Dubai",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MID",
      niches: JSON.stringify(["Lifestyle & Fashion", "Travel"]),
      platforms: JSON.stringify(["Instagram", "TikTok"]),
      instagramHandle: "laylamansoori",
      instagramFollowers: 310000,
      tiktokHandle: "laylamansoori",
      tiktokFollowers: 450000,
      tiktokAvgViews: 180000,
      audienceGenderSplit: JSON.stringify({ male: 28, female: 72 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 12, "18-24": 38, "25-34": 36, "35-44": 11, "45+": 3 }),
      audienceTopCountries: JSON.stringify([
        { country: "UAE", percentage: 42 },
        { country: "Saudi Arabia", percentage: 30 },
        { country: "Kuwait", percentage: 10 },
        { country: "Egypt", percentage: 8 },
        { country: "Jordan", percentage: 10 },
      ]),
      audienceInterests: JSON.stringify(["Fashion", "Beauty", "Travel", "Lifestyle", "Food"]),
      rateInstagramPost: 2800,
      rateInstagramStory: 900,
      rateInstagramReel: 3500,
      rateTikTokVideo: 3000,
      rateUGCVideo: 1500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Zara", "H&M", "Marriott", "MAC Cosmetics", "MANGO"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["lifestyle", "fashion", "dubai", "bilingual"]),
      isActive: true,
    },
    // 3. Egyptian food content creator
    {
      name: "Omar Ashraf",
      nameAr: "عمر أشرف",
      bio: "Egyptian food creator exploring the rich culinary heritage of Egypt and the Arab world. TikTok-first creator with viral recipe videos and restaurant reviews. Content is primarily in Egyptian Arabic dialect.",
      profileImageUrl: "https://i.pravatar.cc/400?img=12",
      country: "Egypt",
      city: "Cairo",
      language: JSON.stringify(["Arabic"]),
      tier: "MID",
      niches: JSON.stringify(["Food & Restaurants"]),
      platforms: JSON.stringify(["TikTok", "YouTube"]),
      tiktokHandle: "omar.eats",
      tiktokFollowers: 620000,
      tiktokAvgViews: 350000,
      youtubeHandle: "OmarEatsEG",
      youtubeSubscribers: 890000,
      youtubeAvgViews: 120000,
      audienceGenderSplit: JSON.stringify({ male: 48, female: 52 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 18, "18-24": 42, "25-34": 30, "35-44": 8, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Egypt", percentage: 62 },
        { country: "Saudi Arabia", percentage: 18 },
        { country: "UAE", percentage: 10 },
        { country: "Jordan", percentage: 5 },
        { country: "Kuwait", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Food", "Cooking", "Restaurants", "Egyptian Culture"]),
      rateTikTokVideo: 2500,
      rateYouTubeIntegration: 4500,
      rateYouTubeDedicated: 10000,
      rateUGCVideo: 1200,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["KFC Egypt", "Pepsi", "Heinz", "McDonald's Egypt", "Americana"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["food", "egypt", "arabic", "tiktok-viral"]),
      isActive: true,
    },
    // 4. Saudi tech reviewer - MEGA
    {
      name: "Khalid Al-Otaibi",
      nameAr: "خالد العتيبي",
      bio: "Saudi Arabia's most-watched tech reviewer on YouTube. Reviews smartphones, laptops, and consumer electronics in Arabic with English subtitles. Known for in-depth analysis and honest opinions.",
      profileImageUrl: "https://i.pravatar.cc/400?img=8",
      country: "Saudi Arabia",
      city: "Jeddah",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MEGA",
      niches: JSON.stringify(["Tech & Gadgets"]),
      platforms: JSON.stringify(["YouTube", "Instagram", "Twitter/X"]),
      youtubeHandle: "KhalidTech",
      youtubeSubscribers: 2300000,
      youtubeAvgViews: 650000,
      instagramHandle: "khalidtech_sa",
      instagramFollowers: 480000,
      twitterHandle: "KhalidTechSA",
      twitterFollowers: 210000,
      audienceGenderSplit: JSON.stringify({ male: 88, female: 12 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 15, "18-24": 38, "25-34": 35, "35-44": 10, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 52 },
        { country: "UAE", percentage: 15 },
        { country: "Egypt", percentage: 12 },
        { country: "Kuwait", percentage: 8 },
        { country: "Jordan", percentage: 13 },
      ]),
      audienceInterests: JSON.stringify(["Technology", "Smartphones", "Gadgets", "Reviews"]),
      rateYouTubeIntegration: 25000,
      rateYouTubeDedicated: 55000,
      rateYouTubeShort: 8000,
      rateInstagramPost: 8500,
      rateInstagramReel: 12000,
      rateLiveEventAppearance: 35000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: true,
      pastBrandCollabs: JSON.stringify(["Samsung", "Apple", "Xiaomi", "STC", "Noon", "Amazon SA"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["tech", "youtube", "mega", "arabic", "top-tier"]),
      isActive: true,
    },
    // 5. Jordanian travel creator
    {
      name: "Reem Haddad",
      nameAr: null,
      bio: "Jordanian travel photographer and content creator documenting the Middle East's most beautiful destinations. English-first content with a focus on adventure, culture, and sustainable travel.",
      profileImageUrl: "https://i.pravatar.cc/400?img=16",
      country: "Jordan",
      city: "Amman",
      language: JSON.stringify(["English", "Arabic"]),
      tier: "MID",
      niches: JSON.stringify(["Travel", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["Instagram", "YouTube"]),
      instagramHandle: "reemwanderlust",
      instagramFollowers: 180000,
      youtubeHandle: "ReemHaddadTravel",
      youtubeSubscribers: 65000,
      youtubeAvgViews: 28000,
      audienceGenderSplit: JSON.stringify({ male: 35, female: 65 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 8, "18-24": 32, "25-34": 42, "35-44": 14, "45+": 4 }),
      audienceTopCountries: JSON.stringify([
        { country: "Jordan", percentage: 30 },
        { country: "United States", percentage: 22 },
        { country: "United Kingdom", percentage: 15 },
        { country: "Saudi Arabia", percentage: 18 },
        { country: "UAE", percentage: 15 },
      ]),
      audienceInterests: JSON.stringify(["Travel", "Photography", "Culture", "Adventure", "Middle East"]),
      rateInstagramPost: 1800,
      rateInstagramStory: 600,
      rateInstagramReel: 2500,
      rateYouTubeIntegration: 3500,
      rateUGCVideo: 1000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Royal Jordanian", "Booking.com", "Jordan Tourism Board", "National Geographic"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["travel", "jordan", "english-first", "photography"]),
      isActive: true,
    },
    // 6. Bahraini fashion creator
    {
      name: "Fatima Al-Khalifa",
      nameAr: "فاطمة الخليفة",
      bio: "Bahraini fashion and modest wear influencer. Showcases Gulf fashion aesthetics with a focus on abayas, luxury modest wear, and jewelry. Arabic-first content.",
      profileImageUrl: "https://i.pravatar.cc/400?img=25",
      country: "Bahrain",
      city: "Manama",
      language: JSON.stringify(["Arabic"]),
      tier: "MICRO",
      niches: JSON.stringify(["Lifestyle & Fashion", "Beauty & Skincare"]),
      platforms: JSON.stringify(["Instagram", "TikTok"]),
      instagramHandle: "fatima.khalifa.bh",
      instagramFollowers: 72000,
      tiktokHandle: "fatimakhalifabh",
      tiktokFollowers: 95000,
      tiktokAvgViews: 85000,
      audienceGenderSplit: JSON.stringify({ male: 15, female: 85 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 20, "18-24": 45, "25-34": 28, "35-44": 5, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Bahrain", percentage: 35 },
        { country: "Saudi Arabia", percentage: 35 },
        { country: "Kuwait", percentage: 15 },
        { country: "UAE", percentage: 10 },
        { country: "Qatar", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Fashion", "Modest Wear", "Beauty", "Gulf Lifestyle"]),
      rateInstagramPost: 800,
      rateInstagramStory: 300,
      rateInstagramReel: 1200,
      rateTikTokVideo: 1000,
      rateUGCVideo: 600,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Ounass", "Sivvi", "Huda Beauty", "Namshi"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["fashion", "modest-wear", "bahrain", "arabic"]),
      isActive: true,
    },
    // 7. Saudi esports player - MEGA
    {
      name: "Faisal Al-Ghamdi",
      nameAr: "فيصل الغامدي",
      bio: "Former professional esports player turned full-time content creator. Known for PUBG Mobile and FIFA content. One of TikTok's biggest gaming creators in the Arab world with viral montage videos.",
      profileImageUrl: "https://i.pravatar.cc/400?img=3",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Gaming & Esports"]),
      platforms: JSON.stringify(["TikTok", "YouTube", "Instagram"]),
      tiktokHandle: "FaisalGaming",
      tiktokFollowers: 3100000,
      tiktokAvgViews: 1800000,
      youtubeHandle: "FaisalGamingYT",
      youtubeSubscribers: 980000,
      youtubeAvgViews: 220000,
      instagramHandle: "faisalgaming_",
      instagramFollowers: 650000,
      audienceGenderSplit: JSON.stringify({ male: 90, female: 10 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 38, "18-24": 42, "25-34": 16, "35-44": 3, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 60 },
        { country: "Egypt", percentage: 15 },
        { country: "UAE", percentage: 10 },
        { country: "Kuwait", percentage: 8 },
        { country: "Jordan", percentage: 7 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "Esports", "PUBG", "FIFA", "Streaming"]),
      rateTikTokVideo: 28000,
      rateYouTubeIntegration: 20000,
      rateYouTubeDedicated: 45000,
      rateInstagramPost: 12000,
      rateInstagramReel: 18000,
      rateLiveEventAppearance: 50000,
      exclusivityStatus: "EXCLUSIVE",
      managedByFlamenzi: true,
      pastBrandCollabs: JSON.stringify(["PUBG Mobile", "STC Play", "Pepsi", "Snickers", "Adidas"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "esports", "mega", "tiktok-king", "arabic"]),
      isActive: true,
    },
    // 8. Lebanese beauty creator
    {
      name: "Nadia Khalil",
      nameAr: "نادية خليل",
      bio: "Lebanese beauty and makeup artist turned content creator. Creates tutorials in Arabic, French, and English. Renowned for bridging Western beauty trends with Arab aesthetics.",
      profileImageUrl: "https://i.pravatar.cc/400?img=44",
      country: "Lebanon",
      city: "Beirut",
      language: JSON.stringify(["Arabic", "French", "English"]),
      tier: "MACRO",
      niches: JSON.stringify(["Beauty & Skincare", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["Instagram", "YouTube", "TikTok"]),
      instagramHandle: "nadiakhalilbeauty",
      instagramFollowers: 420000,
      youtubeHandle: "NadiaKhalilBeauty",
      youtubeSubscribers: 620000,
      youtubeAvgViews: 95000,
      tiktokHandle: "nadiakhalil",
      tiktokFollowers: 280000,
      tiktokAvgViews: 120000,
      audienceGenderSplit: JSON.stringify({ male: 12, female: 88 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 22, "18-24": 48, "25-34": 24, "35-44": 5, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Lebanon", percentage: 28 },
        { country: "Saudi Arabia", percentage: 25 },
        { country: "Egypt", percentage: 18 },
        { country: "UAE", percentage: 15 },
        { country: "France", percentage: 14 },
      ]),
      audienceInterests: JSON.stringify(["Beauty", "Makeup", "Skincare", "Fashion", "Lifestyle"]),
      rateInstagramPost: 5500,
      rateInstagramStory: 1800,
      rateInstagramReel: 7000,
      rateYouTubeIntegration: 10000,
      rateYouTubeDedicated: 22000,
      rateTikTokVideo: 6000,
      rateUGCVideo: 3500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["L'Oreal Paris", "Maybelline", "Charlotte Tilbury", "Fenty Beauty", "MAC"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["beauty", "lebanon", "multilingual", "macro"]),
      isActive: true,
    },
    // 9. Kuwaiti finance creator
    {
      name: "Ahmad Al-Sabah",
      nameAr: "أحمد الصباح",
      bio: "Kuwaiti financial educator and investment content creator. Breaks down complex financial concepts for Arab millennials. Active on Twitter/X and YouTube with a growing subscriber base.",
      profileImageUrl: "https://i.pravatar.cc/400?img=7",
      country: "Kuwait",
      city: "Kuwait City",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MID",
      niches: JSON.stringify(["Finance & Business"]),
      platforms: JSON.stringify(["Twitter/X", "YouTube"]),
      twitterHandle: "AhmadAlSabahFin",
      twitterFollowers: 180000,
      youtubeHandle: "AhmadFinanceAr",
      youtubeSubscribers: 240000,
      youtubeAvgViews: 55000,
      audienceGenderSplit: JSON.stringify({ male: 72, female: 28 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 5, "18-24": 28, "25-34": 45, "35-44": 18, "45+": 4 }),
      audienceTopCountries: JSON.stringify([
        { country: "Kuwait", percentage: 38 },
        { country: "Saudi Arabia", percentage: 30 },
        { country: "UAE", percentage: 18 },
        { country: "Bahrain", percentage: 8 },
        { country: "Qatar", percentage: 6 },
      ]),
      audienceInterests: JSON.stringify(["Finance", "Investing", "Real Estate", "Business", "Economy"]),
      rateYouTubeIntegration: 5500,
      rateYouTubeDedicated: 12000,
      rateYouTubeShort: 2000,
      rateUGCVideo: 2500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Boursa Kuwait", "NBK", "Robinhood MENA", "Wio Bank"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["finance", "kuwait", "education", "arabic"]),
      isActive: true,
    },
    // 10. Egyptian fitness creator
    {
      name: "Mohamed Hassan",
      nameAr: "محمد حسن",
      bio: "Egyptian fitness coach and content creator. Posts workout routines, nutrition tips, and transformation stories in Arabic. Has a highly engaged MENA fitness community.",
      profileImageUrl: "https://i.pravatar.cc/400?img=11",
      country: "Egypt",
      city: "Cairo",
      language: JSON.stringify(["Arabic"]),
      tier: "MICRO",
      niches: JSON.stringify(["Sports & Fitness"]),
      platforms: JSON.stringify(["Instagram", "TikTok"]),
      instagramHandle: "coach.mohassan",
      instagramFollowers: 52000,
      tiktokHandle: "coachmohassan",
      tiktokFollowers: 78000,
      tiktokAvgViews: 95000,
      audienceGenderSplit: JSON.stringify({ male: 65, female: 35 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 15, "18-24": 45, "25-34": 32, "35-44": 6, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Egypt", percentage: 58 },
        { country: "Saudi Arabia", percentage: 20 },
        { country: "UAE", percentage: 12 },
        { country: "Jordan", percentage: 5 },
        { country: "Kuwait", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Fitness", "Nutrition", "Gym", "Health", "Bodybuilding"]),
      rateInstagramPost: 700,
      rateInstagramStory: 250,
      rateInstagramReel: 1000,
      rateTikTokVideo: 800,
      rateUGCVideo: 500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["MyProtein", "GNC Egypt", "Under Armour", "Decathlon"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["fitness", "egypt", "micro", "arabic"]),
      isActive: true,
    },
    // 11. Saudi female lifestyle - MACRO
    {
      name: "Nouf Al-Qahtani",
      nameAr: "نوف القحطاني",
      bio: "One of Saudi Arabia's most influential female lifestyle creators. Documents her life in Riyadh — fashion, motherhood, home design, and travel. Deeply connected with the Saudi female audience.",
      profileImageUrl: "https://i.pravatar.cc/400?img=20",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic"]),
      tier: "MACRO",
      niches: JSON.stringify(["Lifestyle & Fashion", "Travel"]),
      platforms: JSON.stringify(["Instagram", "Snapchat"]),
      instagramHandle: "nouf.qahtani",
      instagramFollowers: 1800000,
      snapchatHandle: "noufqahtani",
      snapchatFollowers: 920000,
      audienceGenderSplit: JSON.stringify({ male: 22, female: 78 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 18, "18-24": 35, "25-34": 35, "35-44": 10, "45+": 2 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 78 },
        { country: "UAE", percentage: 10 },
        { country: "Kuwait", percentage: 6 },
        { country: "Bahrain", percentage: 3 },
        { country: "Qatar", percentage: 3 },
      ]),
      audienceInterests: JSON.stringify(["Lifestyle", "Fashion", "Home Design", "Travel", "Motherhood"]),
      rateInstagramPost: 15000,
      rateInstagramStory: 5000,
      rateInstagramReel: 20000,
      rateSnapchatStory: 12000,
      rateLiveEventAppearance: 40000,
      exclusivityStatus: "SOFT",
      managedByFlamenzi: true,
      pastBrandCollabs: JSON.stringify(["Sephora KSA", "Ounass", "Hilton Hotels", "Dyson", "Nissan KSA"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["lifestyle", "saudi-female", "macro", "snapchat", "top-creator"]),
      isActive: true,
    },
    // 12. UAE food blogger - MICRO
    {
      name: "James Wheeler",
      nameAr: null,
      bio: "British expat turned Dubai food blogger. Reviews restaurants across Dubai and the UAE with a focus on hidden gems, new openings, and international cuisines. English-first content.",
      profileImageUrl: "https://i.pravatar.cc/400?img=15",
      country: "UAE",
      city: "Dubai",
      language: JSON.stringify(["English"]),
      tier: "MICRO",
      niches: JSON.stringify(["Food & Restaurants"]),
      platforms: JSON.stringify(["Instagram", "TikTok"]),
      instagramHandle: "jameseats.dubai",
      instagramFollowers: 28000,
      tiktokHandle: "jameseatsdubai",
      tiktokFollowers: 32000,
      tiktokAvgViews: 45000,
      audienceGenderSplit: JSON.stringify({ male: 45, female: 55 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 5, "18-24": 30, "25-34": 45, "35-44": 16, "45+": 4 }),
      audienceTopCountries: JSON.stringify([
        { country: "UAE", percentage: 55 },
        { country: "United Kingdom", percentage: 20 },
        { country: "Saudi Arabia", percentage: 12 },
        { country: "India", percentage: 8 },
        { country: "Australia", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Food", "Restaurants", "Dubai Life", "Expat Living"]),
      rateInstagramPost: 400,
      rateInstagramStory: 150,
      rateInstagramReel: 600,
      rateTikTokVideo: 500,
      rateUGCVideo: 300,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Deliveroo UAE", "Zomato UAE", "Time Out Dubai"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["food", "dubai", "expat", "english", "micro"]),
      isActive: true,
    },
    // 13. UK-based Arab gaming creator - MEGA
    {
      name: "Kareem Mansour",
      nameAr: "كريم منصور",
      bio: "London-based Arab gaming creator with one of YouTube's biggest gaming channels from the MENA diaspora. Creates in English with a global audience. Known for GTA, Minecraft, and gaming commentary.",
      profileImageUrl: "https://i.pravatar.cc/400?img=2",
      country: "United Kingdom",
      city: "London",
      language: JSON.stringify(["English", "Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Gaming & Esports", "Comedy & Entertainment"]),
      platforms: JSON.stringify(["YouTube", "Twitch", "TikTok"]),
      youtubeHandle: "KareemGaming",
      youtubeSubscribers: 4200000,
      youtubeAvgViews: 1200000,
      twitchHandle: "KareemLive",
      twitchFollowers: 580000,
      twitchAvgCCV: 22000,
      tiktokHandle: "kareemgaming",
      tiktokFollowers: 890000,
      tiktokAvgViews: 520000,
      audienceGenderSplit: JSON.stringify({ male: 80, female: 20 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 32, "18-24": 48, "25-34": 16, "35-44": 3, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "United Kingdom", percentage: 30 },
        { country: "United States", percentage: 28 },
        { country: "Saudi Arabia", percentage: 18 },
        { country: "UAE", percentage: 12 },
        { country: "Egypt", percentage: 12 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "YouTube", "Comedy", "Streaming", "Pop Culture"]),
      rateYouTubeIntegration: 45000,
      rateYouTubeDedicated: 90000,
      rateTwitchStream: 18000,
      rateTikTokVideo: 22000,
      rateLiveEventAppearance: 60000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["G-Fuel", "NordVPN", "Raid Shadow Legends", "EA Sports", "PlayStation"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "uk-arab", "mega", "english", "global"]),
      isActive: true,
    },
    // 14. Saudi motorsports creator
    {
      name: "Sultan Al-Faisal",
      nameAr: "سلطان الفيصل",
      bio: "Saudi motorsports enthusiast and creator documenting the Saudi racing scene, car culture, and international racing events. Known for cinematic car content and track day videos.",
      profileImageUrl: "https://i.pravatar.cc/400?img=6",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MACRO",
      niches: JSON.stringify(["Motorsports", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["TikTok", "Instagram", "YouTube"]),
      tiktokHandle: "sultancars",
      tiktokFollowers: 380000,
      tiktokAvgViews: 480000,
      instagramHandle: "sultan.motors",
      instagramFollowers: 560000,
      youtubeHandle: "SultanMotorsYT",
      youtubeSubscribers: 180000,
      youtubeAvgViews: 85000,
      audienceGenderSplit: JSON.stringify({ male: 88, female: 12 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 12, "18-24": 38, "25-34": 35, "35-44": 12, "45+": 3 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 65 },
        { country: "UAE", percentage: 20 },
        { country: "Kuwait", percentage: 8 },
        { country: "Bahrain", percentage: 4 },
        { country: "Qatar", percentage: 3 },
      ]),
      audienceInterests: JSON.stringify(["Cars", "Motorsports", "Racing", "Luxury Cars", "Tech"]),
      rateTikTokVideo: 5500,
      rateInstagramPost: 5000,
      rateInstagramReel: 8000,
      rateYouTubeIntegration: 9000,
      rateLiveEventAppearance: 25000,
      rateUGCVideo: 3000,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["BMW KSA", "Shell Helix", "Pirelli", "Saudia Airlines", "G-Shock"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["motorsports", "cars", "saudi", "macro"]),
      isActive: true,
    },
    // 15. Jordanian tech startup founder - MICRO
    {
      name: "Dina Khalaf",
      bio: "Jordanian startup founder and entrepreneur turned LinkedIn creator. Shares insights on building tech companies in MENA, fundraising, and women in tech. Bilingual content.",
      profileImageUrl: "https://i.pravatar.cc/400?img=35",
      country: "Jordan",
      city: "Amman",
      language: JSON.stringify(["English", "Arabic"]),
      tier: "MICRO",
      niches: JSON.stringify(["Finance & Business", "Tech & Gadgets"]),
      platforms: JSON.stringify(["LinkedIn", "Twitter/X"]),
      twitterHandle: "dinakhalaf_jo",
      twitterFollowers: 38000,
      audienceGenderSplit: JSON.stringify({ male: 55, female: 45 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 2, "18-24": 20, "25-34": 50, "35-44": 22, "45+": 6 }),
      audienceTopCountries: JSON.stringify([
        { country: "Jordan", percentage: 35 },
        { country: "UAE", percentage: 25 },
        { country: "Saudi Arabia", percentage: 20 },
        { country: "United States", percentage: 12 },
        { country: "United Kingdom", percentage: 8 },
      ]),
      audienceInterests: JSON.stringify(["Startups", "Technology", "Entrepreneurship", "Women in Tech", "MENA Business"]),
      rateUGCVideo: 1500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Microsoft MENA", "AWS", "Wamda", "Flat6Labs"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["startup", "tech", "jordan", "linkedin", "female"]),
      isActive: true,
    },
    // 16. Egyptian gaming streamer - Kick
    {
      name: "Youssef Adel",
      nameAr: "يوسف عادل",
      bio: "Egyptian live streaming pioneer on Kick platform. Arabic gaming content with a focus on FPS games and esports commentary. One of the first Arab creators to build a major following on Kick.",
      profileImageUrl: "https://i.pravatar.cc/400?img=10",
      country: "Egypt",
      city: "Alexandria",
      language: JSON.stringify(["Arabic"]),
      tier: "MID",
      niches: JSON.stringify(["Gaming & Esports"]),
      platforms: JSON.stringify(["Kick", "TikTok"]),
      kickHandle: "YoussefPlays",
      kickFollowers: 85000,
      kickAvgCCV: 3200,
      tiktokHandle: "youssefgaming_eg",
      tiktokFollowers: 120000,
      tiktokAvgViews: 180000,
      audienceGenderSplit: JSON.stringify({ male: 87, female: 13 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 35, "18-24": 48, "25-34": 14, "35-44": 2, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Egypt", percentage: 65 },
        { country: "Saudi Arabia", percentage: 15 },
        { country: "Jordan", percentage: 8 },
        { country: "UAE", percentage: 7 },
        { country: "Kuwait", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Gaming", "Kick", "Streaming", "FPS", "Esports"]),
      rateKickStream: 2000,
      rateTikTokVideo: 1500,
      rateUGCVideo: 800,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Kick.com", "GFuel Egypt", "HyperX"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["gaming", "kick", "egypt", "arabic", "mid"]),
      isActive: true,
    },
    // 17. UAE luxury lifestyle - MACRO
    {
      name: "Sophia Eriksson",
      bio: "Swedish-born Dubai resident and luxury lifestyle creator. Documents the ultra-premium side of Dubai — supercars, private jets, luxury hotels, and fine dining. English-language content with a global affluent audience.",
      profileImageUrl: "https://i.pravatar.cc/400?img=40",
      country: "UAE",
      city: "Dubai",
      language: JSON.stringify(["English"]),
      tier: "MACRO",
      niches: JSON.stringify(["Lifestyle & Fashion", "Travel", "Luxury & High-End"]),
      platforms: JSON.stringify(["Instagram", "YouTube"]),
      instagramHandle: "sophiadubailux",
      instagramFollowers: 920000,
      youtubeHandle: "SophiaDubaiLux",
      youtubeSubscribers: 185000,
      youtubeAvgViews: 62000,
      audienceGenderSplit: JSON.stringify({ male: 42, female: 58 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 5, "18-24": 25, "25-34": 40, "35-44": 22, "45+": 8 }),
      audienceTopCountries: JSON.stringify([
        { country: "UAE", percentage: 35 },
        { country: "United States", percentage: 25 },
        { country: "United Kingdom", percentage: 18 },
        { country: "Saudi Arabia", percentage: 12 },
        { country: "Australia", percentage: 10 },
      ]),
      audienceInterests: JSON.stringify(["Luxury", "Travel", "Cars", "Fine Dining", "Fashion", "Real Estate"]),
      rateInstagramPost: 9500,
      rateInstagramStory: 3000,
      rateInstagramReel: 13000,
      rateYouTubeIntegration: 15000,
      rateYouTubeDedicated: 32000,
      rateLiveEventAppearance: 30000,
      exclusivityStatus: "SOFT",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Rolls Royce", "Burj Al Arab", "Bulgari", "Louis Vuitton", "Emirates Airlines"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["luxury", "dubai", "english", "macro", "global-audience"]),
      isActive: true,
    },
    // 18. Saudi comedy creator - MEGA
    {
      name: "Hamad Al-Zahrani",
      nameAr: "حمد الزهراني",
      bio: "Saudi comedy and entertainment creator. Known for sketch comedy, reactions, and cultural satire. Huge TikTok and Snapchat following with daily content. One of the most viral Arabic comedians online.",
      profileImageUrl: "https://i.pravatar.cc/400?img=4",
      country: "Saudi Arabia",
      city: "Jeddah",
      language: JSON.stringify(["Arabic"]),
      tier: "MEGA",
      niches: JSON.stringify(["Comedy & Entertainment", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["TikTok", "Snapchat", "Instagram"]),
      tiktokHandle: "HamadComedy",
      tiktokFollowers: 2700000,
      tiktokAvgViews: 3500000,
      snapchatHandle: "hamadzahrani",
      snapchatFollowers: 1800000,
      instagramHandle: "hamad.zahrani",
      instagramFollowers: 890000,
      audienceGenderSplit: JSON.stringify({ male: 60, female: 40 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 30, "18-24": 45, "25-34": 20, "35-44": 4, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 70 },
        { country: "UAE", percentage: 12 },
        { country: "Kuwait", percentage: 8 },
        { country: "Egypt", percentage: 5 },
        { country: "Bahrain", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Comedy", "Entertainment", "Viral Content", "Saudi Culture"]),
      rateTikTokVideo: 32000,
      rateSnapchatStory: 20000,
      rateInstagramPost: 18000,
      rateInstagramReel: 28000,
      rateLiveEventAppearance: 70000,
      exclusivityStatus: "EXCLUSIVE",
      managedByFlamenzi: true,
      pastBrandCollabs: JSON.stringify(["Pepsi KSA", "Chips Oman", "STC", "jarir Bookstore", "Almarai"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["comedy", "mega", "saudi", "snapchat", "viral", "top-creator"]),
      isActive: true,
    },
    // 19. Moroccan travel + lifestyle
    {
      name: "Yasmine Benali",
      nameAr: "ياسمين بنعلي",
      bio: "Moroccan travel and lifestyle creator documenting North Africa, Europe, and the Middle East. Trilingual content in French, Arabic, and English. Known for stunning visual storytelling.",
      profileImageUrl: "https://i.pravatar.cc/400?img=36",
      country: "Morocco",
      city: "Casablanca",
      language: JSON.stringify(["French", "Arabic", "English"]),
      tier: "MID",
      niches: JSON.stringify(["Travel", "Lifestyle & Fashion"]),
      platforms: JSON.stringify(["Instagram", "YouTube"]),
      instagramHandle: "yasmine.maroc",
      instagramFollowers: 280000,
      youtubeHandle: "YasmineTravel",
      youtubeSubscribers: 380000,
      youtubeAvgViews: 78000,
      audienceGenderSplit: JSON.stringify({ male: 38, female: 62 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 10, "18-24": 35, "25-34": 38, "35-44": 13, "45+": 4 }),
      audienceTopCountries: JSON.stringify([
        { country: "Morocco", percentage: 32 },
        { country: "France", percentage: 25 },
        { country: "Algeria", percentage: 15 },
        { country: "Tunisia", percentage: 12 },
        { country: "UAE", percentage: 16 },
      ]),
      audienceInterests: JSON.stringify(["Travel", "Photography", "Moroccan Culture", "Europe", "Food"]),
      rateInstagramPost: 2500,
      rateInstagramStory: 800,
      rateInstagramReel: 3500,
      rateYouTubeIntegration: 5000,
      rateYouTubeDedicated: 11000,
      rateUGCVideo: 1500,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Royal Air Maroc", "Booking.com", "Airbnb", "Morocco Tourism", "Longines"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["travel", "morocco", "multilingual", "mid", "north-africa"]),
      isActive: true,
    },
    // 20. Saudi female tech creator
    {
      name: "Hessa Al-Dossari",
      nameAr: "حصة الدوسري",
      bio: "Saudi female tech creator breaking barriers in the Arab tech space. Reviews gadgets, shares coding tips, and advocates for women in STEM. TikTok-first with growing Instagram presence.",
      profileImageUrl: "https://i.pravatar.cc/400?img=48",
      country: "Saudi Arabia",
      city: "Riyadh",
      language: JSON.stringify(["Arabic", "English"]),
      tier: "MID",
      niches: JSON.stringify(["Tech & Gadgets", "Education"]),
      platforms: JSON.stringify(["TikTok", "Instagram"]),
      tiktokHandle: "hessa.tech",
      tiktokFollowers: 150000,
      tiktokAvgViews: 220000,
      instagramHandle: "hessa.tech",
      instagramFollowers: 190000,
      audienceGenderSplit: JSON.stringify({ male: 35, female: 65 }),
      audienceAgeBreakdown: JSON.stringify({ "13-17": 20, "18-24": 45, "25-34": 28, "35-44": 6, "45+": 1 }),
      audienceTopCountries: JSON.stringify([
        { country: "Saudi Arabia", percentage: 68 },
        { country: "UAE", percentage: 14 },
        { country: "Egypt", percentage: 8 },
        { country: "Jordan", percentage: 5 },
        { country: "Kuwait", percentage: 5 },
      ]),
      audienceInterests: JSON.stringify(["Tech", "Coding", "STEM", "Women in Tech", "Gadgets", "AI"]),
      rateInstagramPost: 2200,
      rateInstagramStory: 700,
      rateInstagramReel: 3000,
      rateTikTokVideo: 2500,
      rateUGCVideo: 1200,
      exclusivityStatus: "NONE",
      managedByFlamenzi: false,
      pastBrandCollabs: JSON.stringify(["Google Arabia", "Microsoft KSA", "Huawei", "Dell KSA"]),
      blacklistedBrands: JSON.stringify([]),
      tags: JSON.stringify(["tech", "saudi-female", "stem", "mid", "arabic"]),
      isActive: true,
    },
  ]

  for (const creator of creators) {
    await prisma.creator.create({ data: creator as any })
  }

  console.log(`✅ Seeded ${creators.length} creators`)
  console.log("✅ Agency settings created")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
